### ISSUE TITLE
Fail to compile on last stable version 5.1.3

### ISSUE THREAD

**Issue by gantispam** [gid-oss/dataui-nestjs-crud#8]
* Error message on compilation step : 
```
node_modules/@dataui/crud/lib/interfaces/auth-options.interface.d.ts(2,31): error TS2307: Cannot find module '@dataui/crud-util/src' or its corresponding type declarations.
```

* Solution : patch this file : https://github.com/gid-oss/dataui-nestjs-crud/blob/v5.1.3/packages/crud/src/interfaces/auth-options.interface.ts
```
import { SCondition } from '@dataui/crud-request/lib/types/request-query.types';
import { ObjectLiteral } from 'crud-util/src';

export interface AuthGlobalOptions {
  property?: string;
}

export interface AuthOptions {
  property?: string;
  filter?: (req: any) => SCondition | void;
  or?: (req: any) => SCondition | void;
  persist?: (req: any) => ObjectLiteral;
}
```

to 
```
import { SCondition } from '@dataui/crud-request/lib/types/request-query.types';
import { ObjectLiteral } from '@dataui/crud-util/lib/types/object-literal.type';
export interface AuthGlobalOptions {
    property?: string;
}
export interface AuthOptions {
    property?: string;
    filter?: (req: any) => SCondition | void;
    or?: (req: any) => SCondition | void;
    persist?: (req: any) => ObjectLiteral;
}

```

**Comment by zaro** [comment]
@gantispam  please check the last 5.2.1 version, this should be fixed there. Reopen if you have problems.
